name = "ParzzixMB"
license = "MIT"
licenselink = "https://github.com/timappledotcom/ParzzixMB/blob/main/LICENSE"
description = "A clean, minimalist Hugo theme designed for microblogging with dual content types: long-form blog posts and short microblog entries."
homepage = "https://github.com/timappledotcom/ParzzixMB"
tags = ["blog", "microblog", "minimal", "clean", "responsive", "typography", "fast", "simple"]
features = ["responsive", "microblog", "timeline", "dual-content", "minimal-design", "fast-loading", "accessibility"]
min_version = "0.80.0"

# Micro.blog specific configuration
[microblog]
  version = "1.0"
  posts_section = "posts"
  blog_section = "blog" 
  timeline_posts = 20

[author]
  name = "Tim Apple"
  homepage = "https://github.com/timappledotcom"
